branch-defaults:
  master:
    environment: Sample-env
environment-defaults:
  Sample-env:
    branch: null
    repository: null
global:
  application_name: Sunlight Web Application
  default_ec2_keyname: Sunlight
  default_platform: Node.js
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
